### ISSUE TITLE
Chapter 6, Basic Interactor isn't compiling

### ISSUE THREAD

**Issue by tacman** [PacktPublishing/Unity-2020-Virtual-Reality-Projects-3rd-Edition-#2]
I imagine something has changed in the API, I'm getting these two errors now.  But it's only in the Chapter 6 file.  When I comment out this class, things seem to work.

BTW, XR Interaction Toolkit is very close to actual release!

Assets\_UWVRP3Assets\Chapter06\Scripts\BasicInteractor.cs(8,49): error CS0115: 'BasicInteractor.ValidTargets': no suitable method found to override

Assets\_UWVRP3Assets\Chapter06\Scripts\BasicInteractor.cs(4,14): error CS0534: 'BasicInteractor' does not implement inherited abstract member 'XRBaseControllerInteractor.validTargets.get'

```csharp
using System.Collections.Generic;
using UnityEngine.XR.Interaction.Toolkit;

public class BasicInteractor : XRBaseControllerInteractor
{
    public override void GetValidTargets(List<XRBaseInteractable> validTargets) { }

    protected override List<XRBaseInteractable> ValidTargets { get; }
}
```

**Comment by linojon** [comment]
Yes, I should have avoided putting that kind of dependency into a book! For an alternative solution to gaze based interactions (e.g. for Google Cardboard) you can see the article i wrote last year and corresponding GitHub repository https://medium.com/@linojon/an-xr-cardboard-interactor-for-unity-eec6270be2e9. I will publish an addendum and update the GitHub projects after XR Interaction Toolkit 1.0 is officially released.
