### ISSUE TITLE
Cannot Unzip Chapter Zip File

### ISSUE THREAD

**Issue by MikeSparkes** [PacktPublishing/Unity-2020-Virtual-Reality-Projects-3rd-Edition-#4]
Hi

The Chapter zip files are 1kb each and when opening I get the error that the file is invalid?

Thanks

Mike

**Comment by linojon** [comment]
Please make sure you have Git LFS installed and when you are cloning or pulling the repository it has successfully downloaded all the LFS (large files) types identified in the .gitattributes file. See https://github.com/git-lfs/git-lfs/wiki/Installation

**Comment by MikeSparkes** [comment]
Thanks Jonathan.

Also is it possible to get the electronic version of the book, or do I have to buy it again. I only ask because the book has lots of URLs and mentions copying and pasting which is obviously not possible with paper

Cheers

Mike

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
